name: Deploy Backend Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker info    
      - name: Build Docker Image
        run: docker build -t jaisanth123/attendancesync-server -f ./backend/Dockerfile .
      - name: Publish Image to Docker Hub
        run: docker push jaisanth123/attendancesync-server:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from Docker Hub
        run: docker pull jaisanth123/attendancesync-server:latest 
      - name: Delete old container
        run: docker rm -f attendancesync-server-container  
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 \
            --name attendancesync-server-container \
            -e JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}' \
            -e JWT_EXPIRE='${{ secrets.JWT_EXPIRE }}' \
            -e COOKIE_EXPIRE='${{ secrets.COOKIE_EXPIRE }}' \
            -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
            jaisanth123/attendancesync-server:latest
