name: Deploy Backend Application

on: 
  push:
    branches:
      - awsDeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t rashmika007/attendancesync-server -f ./backend/Dockerfile .
      - name: Publish Image to Docker Hub
        run: docker push rashmika007/attendancesync-server:latest 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull image from Docker Hub
        run: docker pull rashmika007/attendancesync-server:latest 
      - name: Delete old container
        run: docker rm -f attendancesync-server-container  
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 \
            --name attendancesync-server-container \
            -e JWT_SECRET_KEY='${{ secrets.JWT_SECRET_KEY }}' \
            -e JWT_EXPIRE='${{ secrets.JWT_EXPIRE }}' \
            -e COOKIE_EXPIRE='${{ secrets.COOKIE_EXPIRE }}' \
            -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' \
            rashmika007/attendancesync-server:latest
