name: Deploy React Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
       run: |
         echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
         docker info  
      - name: Build Docker Image
        run: docker build -t jaisanth123/attendancesync -f ./frontend/Dockerfile --build-arg VITE_BACKEND_URL='${{ secrets.VITE_BACKEND_URL }}' .
      - name: Publish Image to Docker Hub
        run: docker push jaisanth123/attendancesync:latest 

  deploy:
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull jaisanth123/attendancesync:latest 
      - name: Delete Old Container
        run: docker rm -f attendancesync-container
      - name: Run Docker Container
    needs: build
    runs-on: self-hosted 
        run: docker run -d -p 5173:80 --name attendancesync-container jaisanth123/attendancesync:latest
