name: Deploy React Application

on: 
  push:
    branches:
      - awsDeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t rashmika007/attendancesync -f ./frontend/Dockerfile --build-arg VITE_BACKEND_URL='${{ secrets.VITE_BACKEND_URL }}' .
      - name: Publish Image to Docker Hub
        run: docker push rashmika007/attendancesync:latest 

  deploy:
    needs: build
    runs-on: self-hosted 
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull rashmika007/attendancesync:latest 
      - name: Delete Old Container
        run: docker rm -f attendancesync-container
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name attendancesync-container rashmika007/attendancesync:latest
